### ISSUE TITLE
Version missmatch hanazeder 1.3.0 and hanazeder_server 1.0.1

### ISSUE THREAD

**Issue by da-bernie** [unverbraucht/hanazeder_server#4]
Hallo Herr Read,

ich hab gesehen das Sie die Ausgänge auch noch mit aufgenommen haben. Da habe ich mir gedacht ich aktualisiere mal den Docker-Container. Das funktioniert aber nicht.

Ein
...
pip3 install --no-cache-dir hanazeder_server
...
installiert weiterhin die Versionen hanazeder-1.2.1 hanazeder_server-1.0.1.
Ein
...
pip3 install --no-cache-dir hanazeder==1.3.0 hanazeder_server
...
installiert folgende Versionen hanazeder-1.3.0 hanazeder_server-0.1.0. Ich habe es nicht getestet, aber die 0.1.0 des Servers ist nicht die aktuelle Version.
Mit
...
pip3 install --no-cache-dir hanazeder==1.3.0 hanazeder_server==1.0.1
...
bekomme ich folgende Fehlermeldung:
...
ERROR: Cannot install hanazeder-server==1.0.1 and hanazeder==1.3.0 because these package versions have conflicting dependencies.
...

Wären Sie so freundlich und fixen die Abhängigkeiten? Dann wären meine Anforderungen bezüglich der ausgelesenen Daten vollständig erfüllt und ich könnte von meinem FHEM-Logging zu was " modernen" wechseln.

Vielen Dank, Grüße

Bernhard Hübner

**Comment by unverbraucht** [comment]
Hallo,

ich hab so meine liebe Not mit poetry, das Release wurde wohl nicht sauber zu pypi published. Version 1.1.1 vom server ist jetzt verfügbar und dependet auch sauber auf hanazeder==1.3.0

**Comment by da-bernie** [comment]
Getestet und funktioniert.
Vielen Dank.
